name: Node.js Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 21.x]
    name: Node ${{ matrix.node-version }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
    - run: npm test --workspaces

  release:
    needs: validate
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - uses: google-github-actions/release-please-action@v4
      with:
        # Use GitHub Actions secret with a Personal Access Token as all
        # resources created by release-please (release tag or release pull
        # request) will not trigger future GitHub actions workflows, and
        # workflows normally triggered by release.created events will also
        # not run when used with the default GITHUB_TOKEN.
        token: ${{ secrets.Automation }}
