# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup PNPM
      # You may pin to the exact commit or the version.
      # uses: pnpm/action-setup@935101478d12d633ea2e71bb8b63d18e00bda099
      uses: pnpm/action-setup@v1.2.1
      with:
        # Version of PNPM to install
        version: 5.11
        # Where to store PNPM files
        # dest: # optional, default is ~/setup-pnpm
        # Where to store executables (pnpm and pnpx commands)
        # bin_dest: # optional, default is ~/setup-pnpm/.bin
        # Registry to download PNPM from
        # registry: # optional, default is https://registry.npmjs.com
        # If specified, run `pnpm install`
        run_install: true
    - name: Lint Pkgs
      run: pnpm run lint --filter "@csscolor/*"
    - name: Test Pkgs
      run: pnpm run test --filter "@csscolor/*"
